parameters:
    superrb_redis_handler.redis_url: "%env(resolve:SUPERRB_REDIS_URL)%"
    superrb_redis_handler.redis_prefix: "%env(string:SUPERRB_REDIS_PREFIX)%"

services:
    superrb_redis.service:
        class: Predis\Client
        arguments:
            - '%superrb_redis_handler.redis_url%'
            - {'prefix': '%superrb_redis_handler.redis_prefix%'}

    superrb_redis.session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@superrb_redis.service'
            - {'prefix': 'session_'}

    superrb_redis.doctrine_cache:
        class: Doctrine\Common\Cache\PredisCache
        arguments:
            - '@superrb_redis.service'
        calls:
            -   method: setNamespace
                arguments:
                    - 'doctrine_'

# Set up sessions and cache
#framework:
#    session:
#        handler_id: superrb_redis.session_handler
#    cache:
#        app: cache.adapter.redis
#        system: cache.adapter.redis
#        default_redis_provider: superrb_redis.service

# Set up doctrine cache
#doctrine:
#    orm:
#        metadata_cache_driver:
#            type: service
#            id: superrb_redis.doctrine_cache
#        result_cache_driver:
#            type: service
#            id: superrb_redis.doctrine_cache
#        query_cache_driver:
#            type: service
#            id: superrb_redis.doctrine_cache
